Algoritmo "parimpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/04/2025
Var
procedimento parimpar(a: inteiro)
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
se (a % 2 = 0) entao
   escreval("é par")
senao
   escreval("é impar")
fimse
fimprocedimento

inicio

parimpar(5)

Fimalgoritmo