Algoritmo "TesteVetor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var
v: vetor[1..6] de inteiro
c: inteiro


Inicio
para c <- 1 ate 6 faca
     escreva("digite o ", c ," valor: ")
     leia(v[c])
fimpara
para c <- 1 ate 6 faca
     escreval("o ", c ," valor é: ",v[c])
fimpara
Fimalgoritmo