Algoritmo "matrizpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2025
Var

valores: vetor[1..3, 1..3] de inteiro
l,c: inteiro

Inicio

para l <- 1 ate 3 faca
     para c <- 1 ate 3 faca
        escreva("digite o valor da posicao: ")
        leia(valores[l,c])
     fimpara
fimpara
para c de 1 ate 3 faca


Fimalgoritmo